--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Leonxv/-ver-about-version-Disable
build-by-default: true
branches:
- master
projects:
  -ver-about-version-Disable:
    path: ""
...
