name: Version false
api: [3.0.0,4.0.0]
version: 1.0.0
main: command\Main
load: POSTWORLD
author: Aleondev
commands:
  cmd:
    description: "§ecmd"
    usage: "/cmd"
    permission: cmd.com
permissions:
  cmd.com:
    description: "§ecmd"
    default: op
